spring:
  profiles: default
  zipkin:
    baseUrl: http://localhost:9411
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://tracing-service:9411
server:
  port: 9002
eureka:
  client:
    serviceUrl:
      defaultZone: http://REGISTRY-SERVICE:8761/eureka/